spring:
  application:
    name: flashcard-generator
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/flashcards}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:your-jwt-secret-must-be-at-least-32-characters-long-and-secure}
    expiration: 86400000
  
  claude:
    api-key: ${CLAUDE_API_KEY:your-claude-api-key}
    base-url: https://api.anthropic.com/v1
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true

logging:
  level:
    com.synth.flashcard: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    root: WARN